FROM redis:3.2.12
MAINTAINER shaobo.zheng <shaobo.zheng@xuncetech.com>
COPY redis.conf /data/redis.conf
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && echo 'Asia/Shanghai' >/etc/timezone \
  && chmod 755 /data/redis.conf
EXPOSE 6380 16380
VOLUME ["/data"]
CMD [ "redis-server", "/data/redis.conf" ]
